FROM denoland/deno:alpine

ARG stage
ARG host_endpoint
# ARG uix_args

ENV APP_STAGE=$stage
ENV UIX_HOST_ENDPOINT=$host_endpoint

# Copy repo
WORKDIR /app
COPY ./repo .

EXPOSE 80
{{EXPOSE_DEBUG}}

CMD sh -c "rm -f deno.lock; rm -f ./src/deno.lock; deno upgrade --version 1.39.4 &>/dev/null; deno run --import-map https://cdn.unyt.org/uix/importmap.json -Aqr https://cdn.unyt.org/uix/run.ts --port 80 --stage $APP_STAGE --cache-path /datex-cache {{UIX_ARGS}}"