FROM denoland/deno:bin AS deno
FROM ubuntu
COPY --from=deno /deno /usr/local/bin/deno

ARG stage
ARG host_endpoint
# ARG uix_args

ENV APP_STAGE=$stage
ENV UIX_HOST_ENDPOINT=$host_endpoint

# Copy repo
WORKDIR /app
COPY ./repo .

EXPOSE 80
{{EXPOSE_DEBUG}}

CMD sh -c "rm -f deno.lock; rm -f ./src/deno.lock; deno run --import-map {{IMPORTMAP_PATH}} -Aqr {{UIX_RUN_PATH}} --port 80 --stage $APP_STAGE --cache-path /datex-cache {{UIX_ARGS}}"