FROM ubuntu:latest
RUN apt-get update && apt-get install -y \
	bash \
	unzip \
	curl \
	watchman \
	git

ARG stage
ARG host_endpoint
# ARG uix_args

ENV APP_STAGE=$stage
ENV UIX_HOST_ENDPOINT=$host_endpoint

# Copy repo
WORKDIR /app
COPY ./repo .

EXPOSE 80
{{EXPOSE_DEBUG}}

RUN curl -fsSL https://raw.githubusercontent.com/unyt-org/uix-install/main/install-deno.sh | bash

CMD sh -c "rm -f deno.lock; rm -f ./src/deno.lock; $HOME/.uix/bin/deno run --no-config --import-map {{IMPORTMAP_PATH}} -Aqr {{UIX_RUN_PATH}} --port 80 --stage $APP_STAGE --cache-path /datex-cache {{UIX_ARGS}}"
